### ISSUE TITLE
Tooltips should be able to expand beyond the bounds of the containing element

### ISSUE THREAD

**Issue by chrysb** [quassummanus/SwiftUI-Tooltip#11]
Hey all,

Great initiative. I started to build my own and ran into this issue where I couldn't get the tooltip to expand beyond the frame of what I attach it too. I see that this project has the same issue:

```swift
Circle()
  .fill(Color.green)
  .frame(width: 36, height: 36)
  .tooltip(.top) {
    Text("Tap here")
  }
```

You'll see that the tooltip shows up as just "..." because it's getting truncated and limited to 36px wide.

**Comment by bring-shrubbery** [comment]
Thanks for the issue! I'll take a look at this as soon as I have time!

**Comment by bring-shrubbery** [comment]
Hey @chrysb! Turned out to be a simple fix using `.fixedSize`. You can see implementation in #13
