### ISSUE TITLE
background color , arrow color, border color

### ISSUE THREAD

**Issue by jahnaviShingala** [quassummanus/SwiftUI-Tooltip#3]
how can i change color for background , arrow and border
also i want to add it on bottom of  navigation item
how can i do tht?
. bottom , .bottom trailing , bottom leading not working properly

**Comment by bring-shrubbery** [comment]
Background and border color are now a feature. Was introduced in [v1.1](https://github.com/quassummanus/SwiftUI-Tooltip/releases/tag/v1.1.0) via #4 . You can take a look at README [here](https://github.com/quassummanus/SwiftUI-Tooltip#configuration-reference) to see all configuration options.
